---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: create files
      file:
        path: "/home/ec2-user/{{ item }}"
        state: touch
      loop:
        - test1.txt
        - test2.txt
